[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "fcc-sea-level-predictor"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = "^3.7"
scipy = "*"
